"""文档编写 Skill — doc-writing
================================
生成 API 文档、变更日志、README 等文档内容。
"""

from skills.base import BaseSkill
from datetime import datetime, timezone


class DocWritingSkill(BaseSkill):
    name = "doc-writing"
    version = "1.0.0"
    description = "文档编写：API 文档、变更日志、README 自动生成"

    def execute(self, input_data: dict) -> dict:
        doc_type = input_data.get("doc_type", "api")
        content = input_data.get("content", "")
        title = input_data.get("title", "Untitled")

        if doc_type == "changelog":
            docs = f"""# Changelog — {title}

## [{datetime.now(timezone.utc).strftime('%Y-%m-%d')}]

### Changed
- Updated based on provided content

### Generated by
- Skill: {self.name} v{self.version}
"""
        elif doc_type == "api":
            docs = f"""# API Documentation — {title}

## Overview
{content[:500]}...

## Methods
(To be filled from source analysis)

## Generated by
- Skill: {self.name} v{self.version}
"""
        else:
            docs = f"# {title}\n\n{content}\n\n---\n*Generated by {self.name} v{self.version}*"

        return {
            "skill": self.name,
            "version": self.version,
            "doc_type": doc_type,
            "title": title,
            "doc_length": len(docs),
            "document": docs,
            "status": "ok",
        }

    def validate_input(self, input_data: dict) -> bool:
        return isinstance(input_data, dict) and "doc_type" in input_data and "title" in input_data

    def get_schema(self) -> dict:
        return {
            "input": {
                "type": "object",
                "required": ["doc_type", "title"],
                "properties": {
                    "doc_type": {"type": "string", "enum": ["api", "changelog", "readme"]},
                    "title": {"type": "string", "description": "文档标题"},
                    "content": {"type": "string", "description": "源内容（可选）"},
                },
            },
            "output": {
                "type": "object",
                "properties": {
                    "skill": {"type": "string"},
                    "doc_type": {"type": "string"},
                    "doc_length": {"type": "integer"},
                    "document": {"type": "string"},
                    "status": {"type": "string"},
                },
            },
        }
